In [1]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("iphone_purchase_records.txt")

In [4]:
print(data)

     Gender  Age  Salary  Purchase Iphone
0      Male   19   19000                0
1      Male   35   20000                0
2    Female   26   43000                0
3    Female   27   57000                0
4      Male   19   76000                0
..      ...  ...     ...              ...
395  Female   46   41000                1
396    Male   51   23000                1
397  Female   50   20000                1
398    Male   36   33000                0
399  Female   49   36000                1

[400 rows x 4 columns]


In [8]:
X=data.iloc[:,:-1]
Y=data.iloc[:,3:4]

In [9]:
print(X)

     Gender  Age  Salary
0      Male   19   19000
1      Male   35   20000
2    Female   26   43000
3    Female   27   57000
4      Male   19   76000
..      ...  ...     ...
395  Female   46   41000
396    Male   51   23000
397  Female   50   20000
398    Male   36   33000
399  Female   49   36000

[400 rows x 3 columns]


In [10]:
print(Y)

     Purchase Iphone
0                  0
1                  0
2                  0
3                  0
4                  0
..               ...
395                1
396                1
397                1
398                0
399                1

[400 rows x 1 columns]


In [11]:
X=X.values
Y=Y.values


In [12]:
print(X.shape)
print(Y.shape)

(400, 3)
(400, 1)


In [24]:
from sklearn.preprocessing import LabelEncoder
le =  LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [25]:
print(X)

[[0 19 19000]
 [0 35 20000]
 [0 26 43000]
 ...
 [0 50 20000]
 [0 36 33000]
 [0 49 36000]]


In [26]:
print(X[0:5,0])

[0 0 0 0 0]


In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

In [29]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(300, 3)
(100, 3)
(300, 1)
(100, 1)


In [30]:
from sklearn.tree import DecisionTreeClassifier
sk_tree=DecisionTreeClassifier(criterion='entropy')
sk_tree.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy')

In [31]:
pred=sk_tree.predict(X_test)

In [32]:
print(pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


In [35]:
acc=sk_tree.score(X_test,Y_test)
print(acc*100)

90.0
